# Generated by Django 6.0.8 on 2026-09-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('stage', models.CharField(default='personal', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('journey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.journey')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
