# Generated by Django 6.0.8 on 2026-09-06 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldraft',
            name='stage',
            field=models.CharField(default='personal', max_length=20),
        ),
        migrations.AddField(
            model_name='personaldraft',
            name='omitted_projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='personaldraft',
            name='project_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.PositiveBigIntegerField()),
                ('answers', models.JSONField(default=dict)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_answers', to='checkins.personaldraft')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('draft', 'project_id'), name='one_draft_project_section')],
            },
        ),
    ]
