# Generated by Django 6.0.8 on 2026-09-07 00:17

from django.db import migrations, models


def preserve_seen_saved_questions(apps, schema_editor):
    Draft = apps.get_model('checkins', 'PersonalDraft')
    ProjectDraft = apps.get_model('checkins', 'ProjectDraft')
    for draft in Draft.objects.all().iterator():
        seen = [key for key in ('P1', 'P2', 'P3', 'P4', 'P5') if key in draft.answers]
        for section in ProjectDraft.objects.filter(draft_id=draft.pk):
            seen.extend(f'{section.project_id}:{key}' for key in ('J1', 'J2', 'J3') if key in section.answers)
        draft.seen_slots = seen
        draft.save(update_fields=['seen_slots'])


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_personaldraft_omitted_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldraft',
            name='adaptive_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldraft',
            name='adaptive_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='personaldraft',
            name='adaptive_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='personaldraft',
            name='seen_slots',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(preserve_seen_saved_questions, migrations.RunPython.noop),
    ]
