# Generated by Django 6.0.8 on 2026-09-07 01:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('windows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='membership.organisation')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WindowDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_late', models.BooleanField(default=False)),
                ('projects', models.JSONField(default=list)),
                ('frozen', models.BooleanField(default=False)),
                ('window', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='windows.weeklywindow')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DispatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('invitation', 'Invitation'), ('analysis', 'Analysis')], max_length=10)),
                ('project_id', models.PositiveBigIntegerField(null=True)),
                ('week', models.DateField()),
                ('version', models.CharField(default='analysis1-privacy1-fake1', max_length=64)),
                ('frozen_sources', models.JSONField(default=list)),
                ('state', models.CharField(default='pending', max_length=12)),
                ('enqueue_after', models.DateTimeField()),
                ('enqueue_lease_until', models.DateTimeField(null=True)),
                ('run_lease_until', models.DateTimeField(null=True)),
                ('run_token', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='windows.weeklywindow')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'invitation')), fields=('window', 'version'), name='unique_invitation_dispatch'), models.UniqueConstraint(condition=models.Q(('kind', 'analysis')), fields=('project_id', 'week', 'version'), name='unique_versioned_analysis_job'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'invitation'), ('project_id__isnull', True)), models.Q(('kind', 'analysis'), ('project_id__isnull', False)), _connector='OR'), name='valid_dispatch_kind_scope'), models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'queued', 'running', 'complete', 'unavailable', 'expired'])), name='valid_dispatch_job_state')],
            },
        ),
    ]
