# Generated by Django 6.0.8 on 2026-09-06 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.PositiveBigIntegerField()),
                ('week', models.DateField()),
                ('schema', models.CharField(max_length=40)),
                ('privacy_policy', models.CharField(max_length=20)),
                ('answers', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'default_permissions': (),
                'indexes': [models.Index(fields=['project_id', 'week'], name='feedback_project_week')],
            },
        ),
    ]
