# Generated by Django 6.0.8 on 2026-09-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], default='member', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='membership.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='membership.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], default='member', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_memberships', to='membership.organisationmembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='membership.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='organisationmembership',
            constraint=models.UniqueConstraint(fields=('organisation', 'user'), name='unique_organisation_member'),
        ),
        migrations.AddConstraint(
            model_name='organisationmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['member', 'manager'])), name='valid_organisation_role'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'organisation_membership'), name='unique_project_member'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['member', 'manager'])), name='valid_project_role'),
        ),
    ]
