# Generated by Django 6.0.8 on 2026-09-07 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('windows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.UUIDField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('ambiguous', 'Ambiguous'), ('withheld', 'Withheld')], default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('attempt_started_at', models.DateTimeField(null=True)),
                ('retain_until', models.DateTimeField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows.weeklywindow')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('window', 'principal'), name='one_invitation_principal_window'), models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'sending', 'sent', 'failed', 'ambiguous', 'withheld'])), name='valid_invitation_state')],
            },
        ),
    ]
