# Generated by Django 6.0.8 on 2026-09-07 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=64)),
                ('week', models.DateField()),
                ('audience', models.CharField(choices=[('manager', 'Manager'), ('team', 'Team')], max_length=10)),
                ('privacy_policy', models.CharField(default='1.0', max_length=20)),
                ('state', models.CharField(default='ready', max_length=16)),
                ('content', models.JSONField(blank=True, null=True)),
                ('released_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('project', 'week', 'audience'), name='one_audience_release')],
            },
        ),
        migrations.CreateModel(
            name='ManagerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=64)),
                ('week', models.DateField()),
                ('analysis_version', models.CharField(max_length=64)),
                ('schema', models.CharField(default='manager-report/1.0', max_length=40)),
                ('privacy_policy', models.CharField(default='1.0', max_length=20)),
                ('state', models.CharField(max_length=16)),
                ('artifact', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('project', 'week', 'analysis_version', 'schema', 'privacy_policy'), name='manager_candidate_key')],
            },
        ),
    ]
