# Generated by Django 6.0.8 on 2026-09-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=64)),
                ('week', models.DateField()),
                ('analysis_version', models.CharField(max_length=64)),
                ('schema', models.CharField(default='team-summary/1.0', max_length=40)),
                ('privacy_policy', models.CharField(default='1.0', max_length=20)),
                ('state', models.CharField(max_length=16)),
                ('artifact', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('project', 'week', 'analysis_version', 'schema', 'privacy_policy'), name='team_candidate_key')],
            },
        ),
    ]
