# Generated by Django 6.0.8 on 2026-09-06 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('windows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed', models.BooleanField(default=False)),
                ('retain_until', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.project')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='windows.weeklywindow')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.principal')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(default='project-feedback-v1', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.participation')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('discarded', 'Discarded'), ('expired', 'Expired')], default='open', max_length=10)),
                ('started_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('selected_scopes', models.JSONField(default=list)),
                ('retain_until', models.DateTimeField()),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.principal')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('principal', 'project', 'window'), name='one_principal_project_window'),
        ),
        migrations.AddConstraint(
            model_name='journey',
            constraint=models.UniqueConstraint(fields=('principal', 'week'), name='one_principal_global_journey'),
        ),
        migrations.AddConstraint(
            model_name='journey',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['open', 'completed', 'discarded', 'expired'])), name='valid_journey_state'),
        ),
    ]
