# Generated by Django 6.0.8 on 2026-09-06 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_name', models.CharField(max_length=100)),
                ('week_start', models.DateField()),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.organisation')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EligibilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('manager', 'Manager')], max_length=7)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='window_snapshots', to='membership.projectmembership')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='windows.weeklywindow')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='weeklywindow',
            constraint=models.UniqueConstraint(fields=('organisation', 'week_start'), name='unique_org_local_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklywindow',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at__lt', models.F('closes_at'))), name='window_opens_before_close'),
        ),
        migrations.AddConstraint(
            model_name='eligibilitysnapshot',
            constraint=models.UniqueConstraint(fields=('window', 'membership'), name='unique_window_membership'),
        ),
        migrations.AddConstraint(
            model_name='eligibilitysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['member', 'manager'])), name='valid_snapshot_role'),
        ),
    ]
